version: '3.8'

services:
  spam-detector-test:
    image: spam-detector-app
    container_name: spam-detector-test
    ports:
      - "5000:5000"
    networks:
      - jenkins

  spam-detector-prod:
    image: spam-detector-app
    container_name: spam-detector-prod
    ports:
      - "5050:5000"
    networks:
      - jenkins

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - jenkins

networks:
  jenkins:
    name: jenkins
    external: true
