version: '3.8'

services:
  spam-detector:
    image: spam-detector-app
    container_name: spam-detector-test
    ports:
      - "5000:5000"

  spam-detector-prod:
    image: spam-detector-app
    container_name: spam-detector-prod
    ports:
      - "5050:5000"
